#!/usr/bin/env python3
"""
Fibonacci HEX Palettes  --  SymPy / NumPy port of
`fibonacci_hex_multispiral_rauzy_geometry_lab.html`

Give it a HEX colour; it gives back a list of palettes generated by every
equation in the original tool:

  * six spiral families on the hexagonal HSV wheel
        φ Fibonacci · τ Tribonacci · δ Silver · ρ Plastic · J Julia · B Binet
    (one colour sampled every quarter-turn -- every 45° for Julia -- along
     the spiral that starts at your colour's position on the wheel)
  * Tribonacci Rauzy tri-tile (tiles A / B / C sampled from the wheel)
  * a palette-geometry report for each palette (PCA shape, hull volume,
    gray spread, null-model comparison)

Where SymPy is used
  - the four ratio constants are the dominant roots of their minimal
    polynomials (x²-x-1, x³-x²-x-1, x²-2x-1, x³-x-1)
  - the spiral equations (log spiral, Julia phase modulation, Binet/Fibonacci
    formula) are written symbolically and `lambdify`-ed into NumPy
  - the Rauzy projection vector (τ², τ, 1) is checked, exactly, to be the
    Perron eigenvector of the Tribonacci substitution matrix

Everything is in the wheel's pixel units (default: the HTML's 600-px canvas,
hexagon circumradius R = 273 px) so node radii match the original tool.

Usage
    python fibonacci_hex_palettes.py "#5CF2B2"
    python fibonacci_hex_palettes.py 5cf2b2 --direction both --count 8
    python fibonacci_hex_palettes.py "#C0392B" --families fibonacci binet --json out.json --html out.html
    python fibonacci_hex_palettes.py --equations
    python fibonacci_hex_palettes.py --self-test

Requires: numpy, sympy.   Optional: scipy (hull volume).
"""
from __future__ import annotations

import argparse
import html as _html
import json
import math
import os
import re
import sys
from dataclasses import dataclass, field
from functools import lru_cache
from typing import Callable, Sequence

import numpy as np
import sympy as sp

try:  # optional -- only used for the 3-D convex-hull volume
    from scipy.spatial import ConvexHull, QhullError  # type: ignore
except Exception:  # pragma: no cover
    ConvexHull = None
    QhullError = Exception

TAU2 = 2 * math.pi
HALF_PI = math.pi / 2

# --------------------------------------------------------------------------
# Tool constants (taken from the HTML)
# --------------------------------------------------------------------------
DEFAULT_R_PX = 273.0       # hexagon circumradius on the HTML's 600-px canvas
MIN_RADIUS_PX = 2.4        # spiral stops once it shrinks below this
MIN_ANCHOR_PX = 4.0        # smallest allowed start radius
DEFAULT_DELTA_E_STOP = 12.0  # CIE76 UI-distinctness cutoff; configurable with --delta-e-stop
EDGE_TOL_PX = 0.3          # outward nodes may overshoot the rim by this much
AUTO_IN_THRESHOLD = 0.74   # start in outer 26% of the radius -> spiral inward
VALUE_FLOOR = 0.10         # HTML brightness slider minimum
RAUZY_WORD_LEN = 9000
RAUZY_ANCHOR_REACH = 0.28  # anchored Rauzy centre is kept within .28 R

# ==========================================================================
# 1.  SymPy: constants, equations, Rauzy eigenvector
# ==========================================================================
X = sp.Symbol("x")

RATIO_POLYS = {            # key -> (symbol, minimal polynomial)
    "fibonacci": ("φ", X**2 - X - 1),
    "tribonacci": ("τ", X**3 - X**2 - X - 1),
    "silver": ("δ", X**2 - 2 * X - 1),
    "plastic": ("ρ", X**3 - X - 1),
}


def _dominant_root(poly: sp.Expr) -> sp.Expr:
    roots = sp.real_roots(sp.Poly(poly, X))
    return max(roots, key=lambda r: float(r.evalf(30)))


RATIO_EXACT = {k: _dominant_root(p) for k, (_, p) in RATIO_POLYS.items()}
RATIO = {k: float(v.evalf(30)) for k, v in RATIO_EXACT.items()}
PHI = RATIO["fibonacci"]
TRIBONACCI = RATIO["tribonacci"]

# -- spiral equations (symbolic) ------------------------------------------
t_, r0_, th0_, d_, k_, c_ = sp.symbols("t r_0 theta_0 d k c", real=True)
q_ = sp.Symbol("q", positive=True)

# d = +1 spirals inward (edge -> core), d = -1 outward (core -> edge)
LOG_K = sp.log(q_) / (sp.pi / 2)                      # k = ln(q) / quarter-turn
LOG_R = r0_ * sp.exp(-d_ * k_ * t_)                   # r(t) = r0 e^(-d k t)
LOG_THETA = th0_ + d_ * t_                            # θ(t) = θ0 + d t

_u = th0_ + d_ * t_
JULIA_PHASE = (sp.Rational(13, 100) * sp.sin(2 * _u + c_)
               + sp.Rational(11, 200) * sp.sin(4 * _u - c_)
               + sp.Rational(1, 40) * sp.sin(8 * _u + sp.Rational(17, 10) * c_))
JULIA_THETA = th0_ + d_ * t_ + JULIA_PHASE            # θ(t) = θ0 + d t + φ(t)
JULIA_C = th0_ * sp.Rational(73, 100) + sp.Rational(61, 100)

n_ = sp.Symbol("n", integer=True)
_phi_sym = (1 + sp.sqrt(5)) / 2
BINET = (_phi_sym**n_ - (-1 / _phi_sym)**n_) / sp.sqrt(5)   # F(n)

_log_r = sp.lambdify((t_, r0_, d_, k_), LOG_R, "numpy")
_log_theta = sp.lambdify((t_, th0_, d_), LOG_THETA, "numpy")
_julia_theta = sp.lambdify((t_, th0_, d_, c_), JULIA_THETA, "numpy")
_binet = sp.lambdify(n_, BINET, "numpy")


def fib(n):
    """Fibonacci numbers from Binet's closed form (rounded, as in the HTML)."""
    return np.floor(_binet(np.asarray(n, dtype=float)) + 0.5)


@dataclass(frozen=True)
class Family:
    key: str
    name: str
    symbol: str
    kind: str          # 'log' | 'julia' | 'binet'
    ratio_key: str     # which constant scales the radius
    turn: float        # angle between sampled nodes (rad)
    dt: float          # path step (rad)
    max_steps: int
    blurb: str

    @property
    def ratio(self) -> float:
        return RATIO[self.ratio_key]


FAMILIES: dict[str, Family] = {f.key: f for f in [
    Family("fibonacci", "Fibonacci", "φ", "log", "fibonacci", HALF_PI, .018, 3200,
           "Golden-ratio log spiral: radius changes by φ each 90° turn."),
    Family("tribonacci", "Tribonacci", "τ", "log", "tribonacci", HALF_PI, .018, 3200,
           "Tribonacci-constant log spiral: radius changes by τ ≈ 1.8393 each 90°."),
    Family("silver", "Silver ratio", "δ", "log", "silver", HALF_PI, .018, 3200,
           "Silver-ratio log spiral: radius changes by δ = 1+√2 each 90°."),
    Family("plastic", "Plastic constant", "ρ", "log", "plastic", HALF_PI, .018, 3200,
           "Plastic-constant log spiral: radius changes by ρ ≈ 1.3247 each 90°."),
    Family("julia", "Julia modulated", "J", "julia", "fibonacci", HALF_PI / 2, .015, 4200,
           "Julia-inspired phase modulation on a φ-scaled spiral, nodes every 45° "
           "(exploratory, not a canonical Julia spiral). The phase term is non-zero at t = 0, so node 00 "
           "sits slightly off your exact colour -- same as the HTML."),
    Family("binet", "Binet sequence", "B", "binet", "fibonacci", HALF_PI, .018, 3200,
           "Exact Fibonacci radii F(5+i)/F(5) at each 90° node (reciprocal when "
           "inward), log-interpolated between nodes."),
]}


def _curves(fam: Family, r0: float, th0: float, d: int, bias_pct: float):
    """Return (radius(t), theta(t), effective_ratio) for one spiral."""
    bias = max(0.2, 1 + bias_pct / 100.0)
    q = fam.ratio * bias
    if fam.kind == "log":
        k = math.log(q) / fam.turn
        return (lambda t: _log_r(t, r0, d, k)), (lambda t: _log_theta(t, th0, d) + 0 * t), q
    if fam.kind == "julia":
        k = math.log(q) / HALF_PI
        c = th0 * 0.73 + 0.61
        return (lambda t: _log_r(t, r0, d, k)), (lambda t: _julia_theta(t, th0, d, c)), q
    # binet: Fibonacci-number radii, log-interpolated, bias applied per turn
    base = float(fib(5))

    def radius(t):
        u = np.asarray(t, float) / fam.turn
        u = np.where(np.abs(u - np.rint(u)) < 1e-9, np.rint(u), u)   # snap exact nodes
        i = np.floor(u)
        f = u - i
        a = fib(5 + i) / base
        b = fib(6 + i) / base
        m = np.exp((1 - f) * np.log(a) + f * np.log(b)) * bias ** u
        return r0 * (1.0 / m if d > 0 else m)

    return radius, (lambda t: _log_theta(t, th0, d) + 0 * t), q


# -- Rauzy: exact check that (τ², τ, 1) is the Perron eigenvector -------------
def rauzy_eigen_check() -> dict:
    """Verify M·v = τ·v exactly, reducing modulo τ³ = τ²+τ+1."""
    T = sp.Symbol("T")
    M = sp.Matrix([[1, 1, 1], [1, 0, 0], [0, 1, 0]])      # σ: 1→12, 2→13, 3→1
    v = sp.Matrix([T**2, T, 1])
    minpoly = sp.Poly(T**3 - T**2 - T - 1, T)
    resid = [sp.rem(sp.Poly(sp.expand(e), T), minpoly) for e in (M * v - T * v)]
    return {"matrix": M, "eigenvector": v, "residual_zero": all(r.is_zero for r in resid),
            "char_poly": M.charpoly(T).as_expr()}


# ==========================================================================
# 2.  Hexagonal HSV wheel  (NumPy)
# ==========================================================================
def edge_radius(theta, R=DEFAULT_R_PX):
    """Distance from wheel centre to the hexagon edge in direction θ."""
    diff = np.mod(np.asarray(theta, float) + math.pi / 3 + math.pi / 6, math.pi / 3) - math.pi / 6
    return R * (math.sqrt(3) / 2) / np.cos(diff)


def hsv_to_rgb(h, s, v):
    """HSV -> RGB ints, matching the HTML's rounding (round half up)."""
    h, s, v = np.broadcast_arrays(np.asarray(h, float), np.asarray(s, float), np.asarray(v, float))
    a = np.mod(h, 360.0) / 60.0
    c = s
    x = c * (1 - np.abs(np.mod(a, 2) - 1))
    m = 1 - c
    z = np.zeros_like(a)
    conds = [a < 1, a < 2, a < 3, a < 4, a < 5]
    rr = np.select(conds, [c, x, z, z, x], default=c)
    gg = np.select(conds, [x, c, c, x, z], default=z)
    bb = np.select(conds, [z, z, x, c, c], default=x)
    rgb = (np.stack([rr, gg, bb], -1) + m[..., None]) * 255.0 * v[..., None]
    return np.clip(np.floor(rgb + 0.5), 0, 255).astype(int)


def rgb_to_hsv(rgb: Sequence[int]):
    r, g, b = (c / 255.0 for c in rgb)
    mx, mn = max(r, g, b), min(r, g, b)
    dl = mx - mn
    if dl == 0:
        h = 0.0
    elif mx == r:
        h = 60 * (((g - b) / dl) % 6)
    elif mx == g:
        h = 60 * ((b - r) / dl + 2)
    else:
        h = 60 * ((r - g) / dl + 4)
    return h, (0.0 if mx == 0 else dl / mx), mx


def hex_of(rgb) -> str:
    return "#%02X%02X%02X" % tuple(int(c) for c in rgb)


def parse_hex(text: str) -> tuple[int, int, int]:
    m = re.fullmatch(r"\s*#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})\s*", text or "")
    if not m:
        raise ValueError(f"not a HEX colour: {text!r} (use #RRGGBB or #RGB)")
    h = m.group(1)
    if len(h) == 3:
        h = "".join(ch * 2 for ch in h)
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)



def rgb_to_lab(rgb: Sequence[int]) -> np.ndarray:
    """sRGB (0..255) -> CIE L*a*b* (D65), for perceptual convergence checks."""
    x = np.asarray(rgb, dtype=float) / 255.0
    x = np.where(x <= 0.04045, x / 12.92, ((x + 0.055) / 1.055) ** 2.4)
    X, Y, Z = np.array([
        0.4124564 * x[0] + 0.3575761 * x[1] + 0.1804375 * x[2],
        0.2126729 * x[0] + 0.7151522 * x[1] + 0.0721750 * x[2],
        0.0193339 * x[0] + 0.1191920 * x[1] + 0.9503041 * x[2],
    ]) / np.array([0.95047, 1.0, 1.08883])
    eps, kappa = 216 / 24389, 24389 / 27
    f = lambda t: t ** (1 / 3) if t > eps else (kappa * t + 16) / 116
    fx, fy, fz = f(X), f(Y), f(Z)
    return np.array([116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz)])


def delta_e76(a: Sequence[int], b: Sequence[int]) -> float:
    """CIE76 ΔE. Used only to decide when further convergence nodes stop adding useful separation."""
    return float(np.linalg.norm(rgb_to_lab(a) - rgb_to_lab(b)))


def usable_swatch_prefix(swatches: Sequence["Swatch"], threshold: float = DEFAULT_DELTA_E_STOP) -> tuple[int, list[float]]:
    """Return count before first adjacent ΔE<threshold, plus all adjacent ΔE values measured."""
    if len(swatches) < 2:
        return len(swatches), []
    deltas = [delta_e76(swatches[i - 1].rgb, swatches[i].rgb) for i in range(1, len(swatches))]
    for i, de in enumerate(deltas, start=1):
        if de < threshold:
            return i, deltas
    return len(swatches), deltas


def parse_hex_list(text: str, limit: int = 40) -> list[str]:
    """Pull #RRGGBB / #RGB / bare RRGGBB colours out of arbitrary text."""
    out, seen = [], set()
    for m in re.finditer(r"#([0-9a-f]{6}|[0-9a-f]{3})(?![0-9a-f])|\b([0-9a-f]{6})\b", str(text), re.I):
        h = m.group(1) or m.group(2)
        if not m.group(1) and h.isdigit():
            continue                      # bare all-digit runs are numbers
        if len(h) == 3:
            h = "".join(ch * 2 for ch in h)
        h = "#" + h.upper()
        if h not in seen:
            seen.add(h)
            out.append(h)
    return out[:limit]


def wheel_sample(r, theta, value, R=DEFAULT_R_PX):
    """Colour at polar position (r px, θ rad) on the wheel at brightness `value`."""
    r = np.asarray(r, float)
    theta = np.asarray(theta, float)
    sat = np.clip(r / edge_radius(theta, R), 0, 1)
    hue = np.mod(np.mod((theta + HALF_PI) / TAU2 * 360.0, 360.0) + 360.0, 360.0)
    return hsv_to_rgb(hue, sat, value), hue, sat


# ==========================================================================
# 3.  Spirals -> palettes
# ==========================================================================
@dataclass
class Swatch:
    hex: str
    rgb: tuple[int, int, int]
    label: str
    r_px: float
    hue: float
    sat: float


@dataclass
class Palette:
    key: str
    title: str
    kind: str                       # 'spiral' | 'rauzy'
    formula: str
    swatches: list[Swatch]
    direction: str | None = None
    meta: dict = field(default_factory=dict)
    geometry: dict | None = None

    @property
    def hexes(self) -> list[str]:
        return [s.hex for s in self.swatches]


@dataclass
class Seed:
    hex: str
    rgb: tuple[int, int, int]
    hue: float
    sat: float
    value_in: float
    value_used: float
    theta: float
    r_px: float
    edge_px: float
    auto_direction: str
    radius_px: float
    notes: list[str]


def make_seed(hex_color: str, value: float | None = None, R: float = DEFAULT_R_PX) -> Seed:
    """Invert the wheel: where does this HEX sit (hue = angle, saturation = r/edge)?"""
    rgb = parse_hex(hex_color)
    h, s, v_in = rgb_to_hsv(rgb)
    notes: list[str] = []
    v = v_in if value is None else float(value)
    if value is None and v < VALUE_FLOOR:
        notes.append(f"brightness {v_in:.0%} is below the tool's {VALUE_FLOOR:.0%} minimum; wheel brightness "
                     f"raised to {VALUE_FLOOR:.0%}, so node 00 is a slightly lighter version of your colour "
                     f"(pass --value to override).")
        v = VALUE_FLOOR
    theta = math.radians(h) - HALF_PI
    if max(rgb) == min(rgb):
        theta = -HALF_PI
        notes.append("grey input has no hue: the spiral starts at the wheel's core (hue 0°, top) at the 4-px "
                     "minimum radius, so node 00 is faintly tinted -- same as the HTML.")
    edge = float(edge_radius(theta, R))
    r0 = s * edge
    if r0 < MIN_ANCHOR_PX:
        if max(rgb) != min(rgb):
            notes.append(f"colour is almost grey; start radius raised to the {MIN_ANCHOR_PX:g}-px minimum.")
        r0 = MIN_ANCHOR_PX
    if value is not None and abs(v - v_in) > 1e-9:
        notes.append(f"wheel brightness overridden: {v:.0%} (input was {v_in:.0%}).")
    return Seed(hex_of(rgb), rgb, h, s, v_in, v, theta, r0, edge,
                "in" if r0 / edge >= AUTO_IN_THRESHOLD else "out", R, notes)


def spiral_nodes(fam: Family, seed: Seed, direction: str, bias_pct: float = 0.0) -> dict:
    """Trace one spiral and return its quarter-turn nodes (r, θ), colours and path length."""
    d = 1 if direction == "in" else -1
    R = seed.radius_px
    radius, theta, q = _curves(fam, seed.r_px, seed.theta, d, bias_pct)

    # dense path: runs until it shrinks below 2.4 px (inward) or leaves the hexagon (outward)
    tt = np.arange(fam.max_steps) * fam.dt
    r_path, a_path = radius(tt), theta(tt)
    stop = (r_path < MIN_RADIUS_PX) | ((d < 0) & (r_path > edge_radius(a_path, R)))
    stop[0] = False
    n_keep = int(np.argmax(stop)) if stop.any() else fam.max_steps
    r_path, a_path, tt = r_path[:n_keep], a_path[:n_keep], tt[:n_keep]
    xy = np.stack([r_path * np.cos(a_path), r_path * np.sin(a_path)], 1)
    length = float(np.hypot(*np.diff(xy, axis=0).T).sum()) if n_keep > 1 else 0.0

    # nodes: one per `turn`
    steps = int(math.floor((tt[-1] + 1e-5) / fam.turn))
    idx = np.arange(steps + 1)
    tn = idx * fam.turn
    rn, an = radius(tn), theta(tn)
    ok = ~((rn > edge_radius(an, R) + EDGE_TOL_PX) | (rn < MIN_RADIUS_PX))
    idx, tn, rn, an = idx[ok], tn[ok], rn[ok], an[ok]
    rgb, hue, sat = wheel_sample(rn, an, seed.value_used, R)
    return {"index": idx, "t": tn, "r": rn, "theta": an, "rgb": rgb, "hue": hue, "sat": sat,
            "length": length, "ratio": q}


def _node_label(fam: Family, i: int, t: float) -> str:
    if i == 0:
        return "ORIGIN"
    if fam.kind == "binet":
        return f"F{i + 5}={int(fib(i + 5))} · {i} × 90°"
    if fam.kind == "julia":
        return f"J{i:02d} · {round(math.degrees(t))}°"
    return f"{i} × {round(math.degrees(fam.turn))}°"


def spiral_palette(fam: Family, seed: Seed, direction: str, bias_pct: float = 0.0,
                   count: int | None = None, delta_e_stop: float = DEFAULT_DELTA_E_STOP) -> Palette:
    nd = spiral_nodes(fam, seed, direction, bias_pct)
    raw = [Swatch(hex_of(nd["rgb"][j]), tuple(int(c) for c in nd["rgb"][j]),
                  _node_label(fam, int(nd["index"][j]), float(nd["t"][j])),
                  float(nd["r"][j]), float(nd["hue"][j]), float(nd["sat"][j]))
           for j in range(len(nd["index"]))]
    usable_n, deltas = usable_swatch_prefix(raw, delta_e_stop)
    if count is not None:
        usable_n = min(usable_n, count)
    sw = raw[:usable_n]
    arrow = "inward · edge → core" if direction == "in" else "outward · core → edge"
    ratio_txt = (f"{fam.symbol} = {nd['ratio']:.10f}" if fam.kind != "julia"
                 else f"J / φ = {nd['ratio']:.10f}")
    family_effect = ("90° hue-node skeleton shared by φ/τ/δ/ρ; the ratio changes radial/chroma convergence rate."
                     if fam.kind == "log" else
                     "Julia changes node phase/turn behavior." if fam.kind == "julia" else
                     "Binet uses discrete Fibonacci radii with interpolation.")
    return Palette(fam.key, f"{fam.symbol}  {fam.name} — {arrow}", "spiral", fam.blurb, sw, direction,
                   {"ratio": nd["ratio"], "trace_length_px": nd["length"], "total_nodes": len(nd["index"]),
                    "usable_nodes": usable_n, "delta_e_stop": float(delta_e_stop),
                    "adjacent_delta_e": [float(x) for x in deltas],
                    "stopped_for_delta_e": usable_n < len(raw) and (count is None or usable_n < count),
                    "family_effect": family_effect,
                    "ratio_label": ratio_txt, "turn_deg": math.degrees(fam.turn)})

# ==========================================================================
# 4.  Rauzy tri-tile
# ==========================================================================
@lru_cache(maxsize=1)
def rauzy_base(n_letters: int = RAUZY_WORD_LEN):
    """Rauzy fractal points from the Tribonacci substitution 1→12, 2→13, 3→1.

    Points are projected along the expanding eigenvector v = (τ², τ, 1) onto the
    plane ⟂ v, then recentred and scaled so the larger bbox side spans [-1, 1].
    """
    tau = TRIBONACCI
    v = np.array([tau * tau, tau, 1.0])
    v /= np.linalg.norm(v)
    raw = np.array([1 - v[0] * v[0], -v[0] * v[1], -v[0] * v[2]])
    e1 = raw / np.linalg.norm(raw)
    e2 = np.cross(v, e1)

    sub = {"1": "12", "2": "13", "3": "1"}
    word = "1"
    while len(word) < n_letters:
        word = "".join(sub[c] for c in word)
    word = word[:n_letters]

    tiles = np.frombuffer(word.encode(), dtype=np.uint8).astype(int) - ord("0")
    onehot = np.eye(3, dtype=int)[tiles - 1]
    counts = np.cumsum(onehot, 0) - onehot                 # counts *before* each letter
    pts = np.stack([counts @ e1, counts @ e2], 1)
    lo, hi = pts.min(0), pts.max(0)
    centre, span = (lo + hi) / 2, (hi - lo).max()
    return (pts - centre) / span * 2, tiles


def inside_hex(x, y, R=DEFAULT_R_PX):
    return np.hypot(x, y) <= edge_radius(np.arctan2(y, x), R) + 0.005


def rauzy_palette(seed: Seed, scale_pct: float = 58.0, rotation: float = -0.28,
                  centred: bool = True, title_suffix: str = "") -> Palette:
    R = seed.radius_px
    base, tiles = rauzy_base()
    if centred:
        cx = cy = 0.0
    else:                                                   # centre on the anchor, kept near the core
        cx, cy = seed.r_px * math.cos(seed.theta), seed.r_px * math.sin(seed.theta)
        dist, reach = math.hypot(cx, cy), R * RAUZY_ANCHOR_REACH
        if dist > reach:
            cx, cy = cx * reach / dist, cy * reach / dist
    ca, sa = math.cos(rotation), math.sin(rotation)
    s = R * scale_pct / 100.0 * 0.92
    X_ = cx + (base[:, 0] * ca - base[:, 1] * sa) * s
    Y_ = cy + (base[:, 0] * sa + base[:, 1] * ca) * s
    vis = inside_hex(X_, Y_, R)

    sw, counts = [], []
    for tile in (1, 2, 3):
        m = vis & (tiles == tile)
        name = chr(64 + tile)
        if not m.any():
            sw.append(Swatch("#000000", (0, 0, 0), f"{name} (off-wheel)", 0.0, 0.0, 0.0))
            counts.append(0)
            continue
        px, py = X_[m], Y_[m]
        j = int(np.argmin((px - px.mean()) ** 2 + (py - py.mean()) ** 2))   # visible pixel nearest centroid
        r, a = math.hypot(px[j], py[j]), math.atan2(py[j], px[j])
        rgb, hue, sat = wheel_sample(r, a, seed.value_used, R)
        sw.append(Swatch(hex_of(rgb), tuple(int(c) for c in rgb), f"tile {name} · {int(m.sum()):,} visible pts",
                         r, float(hue), float(sat)))
        counts.append(int(m.sum()))
    where = "centred on the wheel" if centred else "centred near your colour"
    return Palette("rauzy", f"Rauzy tri-tile — {where}{title_suffix}", "rauzy",
                   "Tribonacci Rauzy fractal (stepped line projected along (τ²,τ,1)); each tile contributes "
                   "the visible fractal pixel closest to its centroid.", sw, None,
                   {"scale_pct": scale_pct, "rotation_rad": rotation, "centred": centred, "visible_points": counts})


# ==========================================================================
# 5.  Palette geometry  (PCA shape, hull volume, null models)
# ==========================================================================
GEO_HUES = ["red", "orange", "yellow", "chartreuse", "green", "mint",
            "cyan", "azure", "blue", "violet", "magenta", "rose"]


def _pca(P: np.ndarray):
    mean = P.mean(0)
    D = P - mean
    vals, vecs = np.linalg.eigh(D.T @ D)
    order = np.argsort(vals)[::-1]
    vals = np.clip(vals[order], 0, None)
    vecs = vecs[:, order].T                               # rows = principal axes
    tot = vals.sum()
    f = vals / tot if tot > 0 else np.array([1.0, 0.0, 0.0])
    return mean, vals, vecs, f


def _classify(f, n):
    if n < 2:
        return "NEED 2+ COLORS"
    if n == 2:
        return "SEGMENT"
    if f[0] >= 0.98:
        return "LINE · SPINE"
    if f[2] < 0.0025:
        return "TRIANGLE" if n == 3 else "PLANAR WEDGE"
    if f[2] < 0.04:
        return "FOLDED FAN"
    return "VOLUME · CLOUD"


def _hue_of(rgb) -> float:
    return rgb_to_hsv(rgb)[0] if max(rgb) != min(rgb) else 0.0


def analyze_points(rgbs) -> dict | None:
    P = np.asarray(rgbs, float)
    n = len(P)
    if n == 0:
        return None
    mean, vals, vecs, f = _pca(P)
    vol = 0.0
    if n >= 4 and ConvexHull is not None:
        try:
            vol = float(ConvexHull(P).volume)
        except QhullError:
            vol = 0.0
    gd = np.linalg.norm(P - P.mean(1, keepdims=True), axis=1)       # distance from the gray axis
    gi = int(np.argmax(gd))
    branch = "neutral" if gd[gi] < 8 else GEO_HUES[int(round(_hue_of(P[gi]) / 30)) % 12]
    const_ch = [f"{'RGB'[k]} = {int(P[0, k])}" for k in range(3) if np.all(P[:, k] == P[0, k])]
    mx = P.max(1)
    return {
        "n": n, "mean": mean.tolist(), "shape": _classify(f, n),
        "linearity_pct": float(f[0] * 100), "third_pc_pct": float(f[2] * 100),
        "planarity_pct": float(100 - f[2] * 100),
        "off_plane_max": float(np.abs((P - mean) @ vecs[2]).max()),
        "hull_volume": vol if (n >= 4 and ConvexHull is not None) else None,
        "gray_spread": float(gd[gi]), "gray_branch": branch,
        "pc1_angle_deg": float(math.degrees(math.acos(min(1.0, abs(vecs[0].sum()) / math.sqrt(3))))),
        "face_locked": const_ch,
        "brightness_shell": int(mx[0]) if np.all(mx == mx[0]) and not const_ch else None,
    }


def _third_pc_pct(sets: np.ndarray) -> np.ndarray:
    D = sets - sets.mean(1, keepdims=True)
    w = np.linalg.eigvalsh(np.einsum("tni,tnj->tij", D, D))         # ascending
    w = np.clip(w, 0, None)
    tot = w.sum(1)
    return np.where(tot > 0, w[:, 0] / np.where(tot > 0, tot, 1), 0.0) * 100


def baseline_sets(n: int, value: float, trials: int = 2000) -> dict[str, np.ndarray]:
    """Sorted 3rd-PC variance % for random palettes of n colours (null models)."""
    rng = np.random.default_rng(1234 + n * 97 + int(round(value * 100)))
    out = {}
    out["rgb"] = np.sort(_third_pc_pct(rng.random((trials, n, 3)) * 255))

    need = trials * n                                               # random picks on the hex wheel
    xy = rng.uniform(-1, 1, (need * 3, 2))
    ang = np.arctan2(xy[:, 1], xy[:, 0])
    rad = np.hypot(xy[:, 0], xy[:, 1])
    er = edge_radius(ang, 1.0)
    keep = rad <= er
    xy, ang, rad, er = xy[keep][:need], ang[keep][:need], rad[keep][:need], er[keep][:need]
    rgb = hsv_to_rgb(np.mod((ang + HALF_PI) / TAU2 * 360, 360), np.minimum(1, rad / er), value)
    out["wheel"] = np.sort(_third_pc_pct(rgb.reshape(trials, n, 3).astype(float)))

    k = max(1, n - 1)                                               # neutral ramp + one accent
    ts = np.sort(rng.random((trials, k)) * 255, axis=1)
    ts[:, 0] = rng.random(trials) * 25
    if k > 1:
        ts[:, k - 1] = 220 + rng.random(trials) * 30
    pts = np.clip(ts[..., None] + rng.standard_normal((trials, k, 3)) * 6, 0, 255)
    acc = rng.random((trials, 3)) * 255
    i1 = np.floor(rng.random(trials) * 3).astype(int)
    i2 = (i1 + 1 + np.floor(rng.random(trials) * 2).astype(int)) % 3
    rows = np.arange(trials)
    acc[rows, i1] = 200 + rng.random(trials) * 55
    acc[rows, i2] = rng.random(trials) * 120
    out["ramp"] = np.sort(_third_pc_pct(np.concatenate([pts, acc[:, None, :]], 1)))
    return out


def _stat(sorted_vals: np.ndarray, mine: float) -> dict:
    q = lambda p: float(sorted_vals[min(len(sorted_vals) - 1, int(math.floor(p * (len(sorted_vals) - 1))))])
    flatter = 100.0 * float(np.sum(sorted_vals > mine * (1 + 1e-9) + 1e-12)) / len(sorted_vals)
    return {"median": q(0.5), "p5": q(0.05), "p95": q(0.95), "flatter_than_pct": flatter}


def _verdict(a: dict, st: dict | None) -> str:
    if a["n"] < 3:
        return "Add at least three colors to see a shape."
    bits, f3 = [], a["third_pc_pct"]
    if a["face_locked"]:
        bits.append(f"Face-locked: {', '.join(a['face_locked'])} on every color, so the set lies on one flat face of the RGB cube.")
    elif a["brightness_shell"] is not None:
        bits.append(f"Every color has max(R,G,B) = {a['brightness_shell']}: the set sits on a single brightness shell, "
                    "which is all one wheel brightness can reach.")
    if a["n"] == 3:
        bits.append("Three points always form a flat triangle, so flatness says nothing at n = 3.")
        return " ".join(bits)
    if a["shape"].startswith("LINE"):
        bits.append("Near-linear: the colors move along one axis, like a lightness ramp.")
    elif st:
        if f3 < st["ramp"]["p5"]:
            bits.append("Flatter than almost any neutral ramp + one accent (below its 5th percentile).")
        elif f3 <= st["ramp"]["p95"]:
            bits.append("This flatness is what a neutral ramp plus ONE accent color gives anyway: it follows from "
                        "the construction, not from a hidden pattern.")
        else:
            bits.append("More volume than a neutral ramp + one accent produces, which points to two or more "
                        "independent chroma directions.")
        if "wheel" in st:
            if f3 < st["wheel"]["p5"]:
                bits.append("Flatter than 95% of random wheel picks at this brightness.")
            elif f3 > st["wheel"]["p95"]:
                bits.append("Less flat than 95% of random wheel picks at this brightness.")
            else:
                bits.append("Within the range of random wheel picks at this brightness.")
    return " ".join(bits)


_baseline_cache: dict = {}


def geometry_report(rgbs, value: float, baselines: bool = True, use_wheel_null: bool = True) -> dict | None:
    a = analyze_points(rgbs)
    if a is None or a["n"] < 2:
        return a
    st = None
    if baselines and a["n"] >= 4:
        key = (a["n"], round(value, 2))
        if key not in _baseline_cache:
            _baseline_cache[key] = baseline_sets(a["n"], value)
        sets = _baseline_cache[key]
        f3 = a["third_pc_pct"]
        st = {"rgb": _stat(sets["rgb"], f3), "ramp": _stat(sets["ramp"], f3)}
        if use_wheel_null:
            st["wheel"] = _stat(sets["wheel"], f3)
        a["null_models"] = st
    a["verdict"] = _verdict(a, st)
    return a


# ==========================================================================
# 6.  Top-level API
# ==========================================================================
def generate_palettes(hex_color: str, *, families: Sequence[str] | None = None, direction: str = "both",
                      bias_pct: float = 0.0, value: float | None = None, count: int | None = None,
                      radius_px: float = DEFAULT_R_PX, rauzy: bool = True, rauzy_scale: float = 58.0,
                      rauzy_rotation: float = -0.28, rauzy_spin: int = 1, geometry: bool = True,
                      baselines: bool = True, delta_e_stop: float = DEFAULT_DELTA_E_STOP) -> tuple[Seed, list[Palette]]:
    """HEX -> (seed info, palettes). Auto chooses the direction with more usable ΔE-separated nodes."""
    seed = make_seed(hex_color, value, radius_px)
    keys = list(FAMILIES) if not families or "all" in families else list(families)
    for k in keys:
        if k not in FAMILIES:
            raise ValueError(f"unknown family {k!r}; choose from {', '.join(FAMILIES)}")

    palettes: list[Palette] = []
    for k in keys:
        fam = FAMILIES[k]
        if direction == "auto":
            candidates = {d: spiral_palette(fam, seed, d, bias_pct, count, delta_e_stop) for d in ("in", "out")}
            # Maximise perceptually useful nodes; use the legacy position heuristic only as the tie-breaker.
            preferred = seed.auto_direction
            chosen = max(("in", "out"), key=lambda d: (candidates[d].meta["usable_nodes"], d == preferred))
            pal = candidates[chosen]
            pal.meta["auto_pick"] = True
            pal.meta["auto_reason"] = {
                "rule": "more usable ΔE-separated nodes; legacy wheel-position heuristic breaks ties",
                "in_usable_nodes": candidates["in"].meta["usable_nodes"],
                "out_usable_nodes": candidates["out"].meta["usable_nodes"],
                "legacy_tiebreak": preferred,
            }
            palettes.append(pal)
        else:
            dirs = ["in", "out"] if direction == "both" else [direction]
            for d in dirs:
                pal = spiral_palette(fam, seed, d, bias_pct, count, delta_e_stop)
                pal.meta["legacy_position_pick"] = (d == seed.auto_direction)
                palettes.append(pal)
    if rauzy:
        spin = max(1, int(rauzy_spin))
        for centred in (True, False):
            for i in range(spin):
                rot = rauzy_rotation + TAU2 * i / spin
                suffix = f" (rot {math.degrees(rot) % 360:.0f}°)" if spin > 1 else ""
                palettes.append(rauzy_palette(seed, rauzy_scale, rot, centred, suffix))
    if geometry:
        for p in palettes:
            p.geometry = geometry_report([s.rgb for s in p.swatches], seed.value_used, baselines)
    return seed, palettes

# ==========================================================================
# 7.  Output
# ==========================================================================
def _ansi(rgb, on: bool, width: int = 4) -> str:
    return f"\x1b[48;2;{rgb[0]};{rgb[1]};{rgb[2]}m{' ' * width}\x1b[0m" if on else ""


def render_text(seed: Seed, palettes: list[Palette], color: bool = True, geometry: bool = True) -> str:
    L: list[str] = []
    bar = "═" * 78
    L += [bar, " FIBONACCI HEX PALETTES", bar]
    L.append(f" Input    {_ansi(seed.rgb, color)} {seed.hex}   RGB {seed.rgb[0]}, {seed.rgb[1]}, {seed.rgb[2]}"
             f"   HSV {seed.hue:.1f}° · {seed.sat:.0%} · {seed.value_in:.0%}")
    L.append(f" Wheel    hue {seed.hue:.1f}° → θ = {math.degrees(seed.theta):.1f}° · r = {seed.r_px:.1f} px of "
             f"{seed.edge_px:.1f} px edge ({seed.r_px / seed.edge_px:.0%}) · brightness {seed.value_used:.0%}")
    L.append(f" Legacy   {'INWARD (edge → core)' if seed.auto_direction == 'in' else 'OUTWARD (core → edge)'}"
             f" — wheel-position tie-break only; --direction auto now prefers more usable ΔE-separated nodes")
    L.append(" Family   φ / τ / δ / ρ share the same 90° hue-node skeleton; their ratio changes radial/chroma convergence, not the hue scheme.")
    for n in seed.notes:
        L.append(f" Note     {n}")
    for i, p in enumerate(palettes, 1):
        star = "  ★ AUTO" if p.meta.get("auto_pick") else ("  · legacy position pick" if p.meta.get("legacy_position_pick") else "")
        L += ["", f"── {i:02d}  {p.title}{star} " + "─" * max(2, 68 - len(p.title) - len(star))]
        if p.kind == "spiral":
            L.append(f"   {p.meta['ratio_label']}  ·  usable {p.meta['usable_nodes']} / raw {p.meta['total_nodes']} nodes  ·  "
                     f"ΔE stop {p.meta['delta_e_stop']:.1f}  · trace {p.meta['trace_length_px']:.0f} px")
            L.append(f"   family effect: {p.meta['family_effect']}")
        else:
            L.append(f"   scale {p.meta['scale_pct']:g}% · rotation {math.degrees(p.meta['rotation_rad']):.1f}°")
        for j, s in enumerate(p.swatches):
            L.append(f"   {j:02d} {_ansi(s.rgb, color)} {s.hex}  rgb({s.rgb[0]:>3},{s.rgb[1]:>3},{s.rgb[2]:>3})  "
                     f"{s.hue:5.1f}°  {s.sat:4.0%}  {s.r_px:6.1f}px  {s.label}")
        L.append("   " + " ".join(p.hexes))
        if geometry and p.geometry and p.geometry.get("n", 0) >= 3:
            g = p.geometry
            vol = "n/a" if g["hull_volume"] is None or g["n"] < 4 else f"{g['hull_volume']:,.0f}"
            L.append(f"   shape {g['shape']} · linearity {g['linearity_pct']:.2f}% · planarity {g['planarity_pct']:.3f}%"
                     f" · off-plane {g['off_plane_max']:.2f} · hull vol {vol}"
                     f" · gray spread {g['gray_spread']:.0f} ({g['gray_branch']}) · PC1 {g['pc1_angle_deg']:.1f}° from gray")
            nm = g.get("null_models")
            if nm:
                L.append(f"   flatter than {nm['rgb']['flatter_than_pct']:.0f}% of random RGB sets"
                         + (f", {nm['wheel']['flatter_than_pct']:.0f}% of random wheel picks" if 'wheel' in nm else "")
                         + f", {nm['ramp']['flatter_than_pct']:.0f}% of ramp+accent sets")
            if g.get("verdict"):
                L.append(f"   {g['verdict']}")
    L += ["", bar]
    return "\n".join(L)


def to_json(seed: Seed, palettes: list[Palette]) -> dict:
    def clean(o):
        if isinstance(o, dict):
            return {k: clean(v) for k, v in o.items()}
        if isinstance(o, (list, tuple)):
            return [clean(v) for v in o]
        if isinstance(o, (np.floating, np.integer)):
            return o.item()
        return o
    return clean({
        "engine_notes": {
            "canonical": True,
            "family_semantics": "φ/τ/δ/ρ share the 90-degree hue-node skeleton; ratio changes radial/chroma convergence rate.",
            "usable_nodes": "Spiral palettes stop before the first adjacent CIE76 ΔE below the configured threshold."
        },
        "seed": {"hex": seed.hex, "rgb": seed.rgb, "hue": seed.hue, "saturation": seed.sat,
                 "value_in": seed.value_in, "value_used": seed.value_used, "theta_rad": seed.theta,
                 "r_px": seed.r_px, "edge_px": seed.edge_px, "auto_direction": seed.auto_direction,
                 "radius_px": seed.radius_px, "notes": seed.notes},
        "palettes": [{"key": p.key, "title": p.title, "kind": p.kind, "direction": p.direction,
                      "formula": p.formula, "meta": p.meta, "hexes": p.hexes,
                      "swatches": [s.__dict__ for s in p.swatches], "geometry": p.geometry}
                     for p in palettes]})


def to_html(seed: Seed, palettes: list[Palette]) -> str:
    esc = _html.escape
    lum = lambda c: c[0] * .299 + c[1] * .587 + c[2] * .114
    rows = []
    for p in palettes:
        chips = "".join(
            f'<div class="chip" style="background:{s.hex};color:{"#111" if lum(s.rgb) > 148 else "#fff"}">'
            f'<b>{s.hex}</b><small>{esc(s.label)}</small></div>' for s in p.swatches)
        g = p.geometry
        geo = (f'<p class="geo">{esc(g["shape"])} · linearity {g["linearity_pct"]:.2f}% · planarity '
               f'{g["planarity_pct"]:.3f}% · gray spread {g["gray_spread"]:.0f} ({esc(g["gray_branch"])})</p>'
               if g and g.get("n", 0) >= 2 else "")
        rows.append(f'<section><h2>{esc(p.title)}</h2><p class="f">{esc(p.formula)}</p>'
                    f'<div class="row">{chips}</div><code>{esc(" ".join(p.hexes))}</code>{geo}</section>')
    return f"""<!doctype html><meta charset="utf-8"><title>Palettes for {seed.hex}</title>
<style>body{{background:#0b1420;color:#e8eef0;font:15px/1.5 system-ui,sans-serif;max-width:1100px;margin:30px auto;padding:0 18px}}
h1{{font-size:26px;margin:0}} h2{{font-size:16px;margin:28px 0 2px;color:#ffd98f}} .f,.geo{{color:#9fb4c0;font-size:13px;margin:2px 0 8px}}
.row{{display:flex;flex-wrap:wrap;gap:6px}} .chip{{flex:1 1 92px;min-width:92px;border-radius:10px;padding:14px 8px;display:flex;flex-direction:column;gap:4px}}
.chip b{{font:700 13px ui-monospace,monospace}} .chip small{{font-size:10px;opacity:.8}} code{{display:block;margin-top:8px;color:#9ee9c9;font-size:12px;word-break:break-all}}
.seed{{display:flex;gap:14px;align-items:center;margin:16px 0}} .seed i{{width:64px;height:64px;border-radius:12px;background:{seed.hex}}}</style>
<h1>Fibonacci HEX palettes</h1>
<div class="seed"><i></i><div><b>{seed.hex}</b><br>RGB {', '.join(map(str, seed.rgb))} · HSV {seed.hue:.1f}°, {seed.sat:.0%}, {seed.value_in:.0%}
<br>auto direction: {'inward' if seed.auto_direction == 'in' else 'outward'}</div></div>
{''.join(rows)}"""


def print_equations() -> None:
    sp.init_printing(use_unicode=True)
    print("RATIO CONSTANTS  (dominant real roots)")
    for k, (sym, poly) in RATIO_POLYS.items():
        print(f"  {sym} {k:<10} root of {sp.sstr(poly)} = 0   ≈ {RATIO_EXACT[k].evalf(15)}"
              f"   exact: {RATIO_EXACT[k]}")
    print("\nLOG SPIRAL  (φ, τ, δ, ρ families)   d = +1 inward, −1 outward")
    print(sp.pretty(sp.Eq(sp.Function("r")(t_), LOG_R), wrap_line=False))
    print(sp.pretty(sp.Eq(sp.Function("θ")(t_), LOG_THETA), wrap_line=False))
    print(sp.pretty(sp.Eq(k_, LOG_K), wrap_line=False), "   (q = ratio × scale-adjustment)")
    print("\nJULIA-MODULATED SPIRAL")
    print(sp.pretty(sp.Eq(sp.Function("θ")(t_), JULIA_THETA), wrap_line=False))
    print(sp.pretty(sp.Eq(c_, JULIA_C), wrap_line=False), "   radius = log-spiral law with k = ln(q)/(π/2)")
    print("\nBINET SEQUENCE SPIRAL")
    print(sp.pretty(sp.Eq(sp.Function("F")(n_), BINET), wrap_line=False))
    print("  r(u) = r₀·[F(5+⌊u⌋)/F(5)]^(1−f)·[F(6+⌊u⌋)/F(5)]^f·bias^u  (÷ when inward),  u = t/(π/2), f = u − ⌊u⌋")
    chk = rauzy_eigen_check()
    print("\nRAUZY TRI-TILE")
    print("  substitution 1→12, 2→13, 3→1   incidence matrix M =", chk["matrix"].tolist())
    print("  characteristic polynomial:", chk["char_poly"])
    print("  M·(τ²,τ,1)ᵀ = τ·(τ²,τ,1)ᵀ  exactly (mod τ³=τ²+τ+1):", chk["residual_zero"])


# ==========================================================================
# 8.  Self-test (fixtures taken from the HTML's own self-test)
# ==========================================================================
def self_test() -> bool:
    ok = True

    def check(name, cond):
        nonlocal ok
        ok &= bool(cond)
        print(f"  [{'PASS' if cond else 'FAIL'}] {name}")

    print("self-test")
    check("φ, τ, δ, ρ match the HTML's constants",
          abs(RATIO["fibonacci"] - (1 + 5 ** .5) / 2) < 1e-15 and abs(RATIO["tribonacci"] - 1.839286755214161) < 1e-14
          and abs(RATIO["silver"] - (1 + 2 ** .5)) < 1e-15 and abs(RATIO["plastic"] - 1.324717957244746) < 1e-14)
    check("Binet formula gives F(5..12) = 5 8 13 21 34 55 89 144",
          list(fib(np.arange(5, 13)).astype(int)) == [5, 8, 13, 21, 34, 55, 89, 144])
    check("(τ²,τ,1) is the exact Perron eigenvector of the Tribonacci matrix", rauzy_eigen_check()["residual_zero"])
    rng = np.random.default_rng(7)
    bad = 0
    for rgb in rng.integers(0, 256, (3000, 3)):
        h = hex_of(rgb)
        seed = make_seed(h, R=DEFAULT_R_PX)
        if seed.value_in < VALUE_FLOOR or seed.r_px == MIN_ANCHOR_PX:
            continue                      # floored brightness / near-grey start radius are intentional changes
        back, _, _ = wheel_sample(seed.r_px, seed.theta, seed.value_used)
        bad += hex_of(back) != h
    check("hex → wheel position → hex round-trips exactly (3000 random colours)", bad == 0)
    mk = lambda lst: [parse_hex(h) for h in lst]
    A = analyze_points(mk(["#000000", "#121614", "#f4f6f5", "#c9d1cd", "#5cf2b2"]))
    C = analyze_points(mk(["#050a14", "#0a1428", "#dbe8ff", "#2f7bff", "#33c8ef"]))
    E = analyze_points(mk(["#0D1117", "#171E2B", "#111722", "#080B11"]))
    if ConvexHull is not None:
        check("geometry: grayscale ramp + mint accent is flat, hull volume ≈ 4051.7",
              A["third_pc_pct"] < 1e-3 and abs(A["hull_volume"] - 4051.7) < 2)
    check("geometry: blue set → 3rd PC 1.8224%, FOLDED FAN", abs(C["third_pc_pct"] - 1.8224) < 0.01 and C["shape"] == "FOLDED FAN")
    check("geometry: near-black cluster is a LINE", E["shape"].startswith("LINE"))
    pl = parse_hex_list("page · #0D1117 gradient(105deg,#00E5FF,#3A6BFF 52%,#9D4DFF) rgba(0,229,255,.12) #abc")
    check("HEX-list parser finds 5 colours incl. expanded #abc", len(pl) == 5 and "#AABBCC" in pl)
    seed, pals = generate_palettes("#5CF2B2", direction="both", baselines=False)
    check("generate_palettes: 6 families × 2 directions + 2 Rauzy palettes", len(pals) == 14)
    check("spiral palettes report usable_nodes and ΔE threshold",
          all(p.kind != "spiral" or ("usable_nodes" in p.meta and p.meta["usable_nodes"] <= p.meta["total_nodes"]) for p in pals))
    _, auto_pals = generate_palettes("#FF6B45", families=["fibonacci"], direction="auto", rauzy=False, geometry=False)
    check("auto direction prefers the branch with more usable nodes",
          len(auto_pals) == 1 and auto_pals[0].meta.get("auto_pick") and auto_pals[0].meta["usable_nodes"] >= 2)
    print("ALL PASS" if ok else "SOME CHECKS FAILED")
    return ok


# ==========================================================================
# 9.  CLI
# ==========================================================================
def main(argv: Sequence[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="HEX → Fibonacci / Tribonacci / Silver / Plastic / Julia / Binet spiral palettes + Rauzy tri-tile.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    ap.add_argument("hex", nargs="?", help="colour, e.g. '#5CF2B2', 5cf2b2 or '#0fa'")
    ap.add_argument("--families", nargs="+", default=["all"], metavar="F",
                    help="subset of: " + " ".join(FAMILIES))
    ap.add_argument("--direction", choices=["auto", "in", "out", "both"], default="both",
                    help="both = inward AND outward palettes; auto = choose the direction with more usable ΔE-separated nodes "
                         "(legacy wheel-position heuristic breaks ties)")
    ap.add_argument("--count", type=int, help="cap each spiral palette after perceptual usable-node truncation")
    ap.add_argument("--delta-e-stop", type=float, default=DEFAULT_DELTA_E_STOP,
                    help="stop before the first adjacent convergence node with CIE76 ΔE below this threshold")
    ap.add_argument("--bias", type=float, default=0.0, help="scale adjustment in %% (HTML range −5…+5)")
    ap.add_argument("--value", type=float, help="wheel brightness 0–1 (default: your colour's own HSV value)")
    ap.add_argument("--radius", type=float, default=DEFAULT_R_PX, help="wheel hexagon circumradius in px")
    ap.add_argument("--no-rauzy", action="store_true", help="skip the Rauzy tri-tile palettes")
    ap.add_argument("--rauzy-scale", type=float, default=58.0, help="Rauzy fractal scale in %% (HTML: 18–96)")
    ap.add_argument("--rauzy-rotation", type=float, default=-0.28, help="Rauzy rotation in radians")
    ap.add_argument("--rauzy-spin", type=int, default=1, help="number of evenly spaced Rauzy rotations to emit")
    ap.add_argument("--no-geometry", action="store_true", help="skip the palette-geometry report")
    ap.add_argument("--no-baselines", action="store_true", help="skip the random-palette null models")
    ap.add_argument("--analyze", metavar="TEXT", help="skip generation: run the geometry report on any HEX list in TEXT")
    ap.add_argument("--json", metavar="FILE", help="also write everything as JSON")
    ap.add_argument("--html", metavar="FILE", help="also write a swatch sheet as HTML")
    ap.add_argument("--no-color", action="store_true", help="plain text (no ANSI swatches)")
    ap.add_argument("--force-color", action="store_true", help="emit ANSI truecolor swatches even when piped")
    ap.add_argument("--equations", action="store_true", help="print the SymPy equations and exit")
    ap.add_argument("--self-test", action="store_true", help="run built-in checks and exit")
    a = ap.parse_args(argv)

    if a.equations:
        print_equations()
        return 0
    if a.self_test:
        return 0 if self_test() else 1
    color = not a.no_color and (a.force_color or (sys.stdout.isatty() and "NO_COLOR" not in os.environ))

    if a.analyze:
        hexes = parse_hex_list(a.analyze)
        if len(hexes) < 2:
            print("need at least two HEX colours", file=sys.stderr)
            return 2
        rgbs = [parse_hex(h) for h in hexes]
        v = max(max(c) for c in rgbs) / 255.0
        g = geometry_report(rgbs, v, not a.no_baselines, use_wheel_null=False)
        seed = make_seed(hexes[0])
        sw = [Swatch(h, c, "", 0, 0, 0) for h, c in zip(hexes, rgbs)]
        pal = Palette("pasted", "Pasted HEX list", "pasted", "", sw, geometry=g)
        print(f"{' '.join(hexes)}\n")
        gm = {k: v for k, v in g.items() if k not in ("mean", "null_models")}
        print(json.dumps(gm, indent=2, default=float))
        if g.get("null_models"):
            print(json.dumps(g["null_models"], indent=2))
        return 0

    hex_in = a.hex
    if not hex_in:
        if sys.stdin.isatty():
            hex_in = input("Enter a HEX colour (e.g. #5CF2B2): ").strip()
        else:
            ap.error("a HEX colour is required")
    try:
        seed, pals = generate_palettes(
            hex_in, families=a.families, direction=a.direction, bias_pct=a.bias, value=a.value, count=a.count,
            radius_px=a.radius, rauzy=not a.no_rauzy, rauzy_scale=a.rauzy_scale, rauzy_rotation=a.rauzy_rotation,
            rauzy_spin=a.rauzy_spin, geometry=not a.no_geometry, baselines=not a.no_baselines,
            delta_e_stop=a.delta_e_stop)
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    print(render_text(seed, pals, color=color, geometry=not a.no_geometry))
    if a.json:
        with open(a.json, "w", encoding="utf-8") as fh:
            json.dump(to_json(seed, pals), fh, indent=2)
        print(f"wrote {a.json}")
    if a.html:
        with open(a.html, "w", encoding="utf-8") as fh:
            fh.write(to_html(seed, pals))        print(f"wrote {a.html}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
